add ally skills prospectus
open-life-science/open-life-science.github.io pull request #424
Opened 2022-10-03 17:59 UTC by yochannah

I think we need to add the link to the menu too. and maybe a Table of Contents?

2022-10-11 15:57 UTC, NPDebs requested changes
This is a fine piece of writing @yochannah. 
I've suggested a view adjustments. I hope you don't mind.

2022-10-11 15:57 UTC, NPDebs commented on consulting.md
> +The Open Life Science (OLS) Ally Skills workshop trainers are trained from the Frame Shift Consulting and training materials provided by them are built on the CC BY-SA 4.0 Licensed resources provided
"For any enquiry and details, please..."

Tinny tiny comma missing.

2022-10-11 15:57 UTC, NPDebs commented on consulting.md
> +Often, when we witness oppression, we are so busy being shocked that we can't quickly react. Other times we have plenty of time to react but can’t figure out what to do, or we do something but it tur
Same here.
"Other times, we have..."

2022-10-11 15:57 UTC, NPDebs commented on consulting.md
> +Diverse perspectives and collaboration drive better research and innovation. Meaningful collaborations require careful thinking about pathways and potential barriers to participation. If your suggest
"...where we can explore our privileges, as well as..."

2022-10-11 15:57 UTC, NPDebs commented on consulting.md
> +The workshop is delivered in English. Nonetheless, we are very interested and welcome the possibility to work with a sign language interpreter or translator, please discuss this further with the OLS
"...interpreter or translator. Please discuss..."

2022-10-11 15:57 UTC, NPDebs commented on consulting.md
> +- Different perspectives and experiences of participants enrich the discussion overall, however, participants will not be forced to share their thoughts.
"...enrich the discussion overall. However, participants..."

2022-10-11 15:57 UTC, NPDebs commented on consulting.md
> +- For the session to be effective we recommend no more than three levels of hierarchy attending the workshop, for example, employees, managers, and their managers. Ideally, one level only is better.
"...attending the workshop. For example, employees..."

2022-10-17 12:27 UTC, bebatut commented on consulting.md
> +- OLS post about a previous workshop: https://openlifesci.org/posts/2020/10/05/ally-skills-training/
```suggestion
- [OLS post about a previous workshop]({% link _posts/2020-10-05-ally-skills-training.md %})
```

2022-10-17 12:27 UTC, bebatut commented on consulting.md
> +The Open Life Science (OLS) Ally Skills workshop trainers are trained from the Frame Shift Consulting and training materials provided by them are built on the CC BY-SA 4.0 Licensed resources provided
It is redundant with the introduction paragraph before

2022-10-17 12:27 UTC, bebatut commented on consulting.md
> +- Participants should have access to internet bandwidth for video conferencing. We recommend that the event organisers check if their members may require any audiovisual equipment that can be arrange
```suggestion
- Participants should have access to internet bandwidth for video conferencing.

  We recommend that the event organisers check if their members may require any audiovisual equipment that can be arranged for them in advance.
```

2022-10-17 12:27 UTC, bebatut commented on consulting.md
> +- Report by OLS describing why we discuss Ally Skills in science: https://www.software.ac.uk/blog/2021-07-05-why-we-discuss-ally-skills-open-science
```suggestion
- [Report by OLS describing why we discuss Ally Skills in science](https://www.software.ac.uk/blog/2021-07-05-why-we-discuss-ally-skills-open-science)
```

2023-05-31 13:14 UTC, yochannah commented
@bebatut I think I've merged your changes - okay to merge?

2023-05-31 13:20 UTC, yochannah commented on consulting.md
> +[Download a copy of the course description](https://docs.google.com/document/d/1BfwarY5zR5jFBI_UemDfQdmcHS4nQViar95W2yt8fx8/edit?usp=sharing)
done!

2023-05-31 13:40 UTC, bebatut commented
Should we make that visible from the navbar?

2023-06-01 06:04 UTC, bebatut approved these changes

2023-06-01 06:04 UTC, merged